# Site settings
title: 管登荣
description: '即使生命如尘，但愿岁月如歌'
url: 'http://DengrongGuan12.github.com/blog' 
baseurl: '/blog/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: '管登荣'
  email: 15950570277@163.com
  twitter_username: DengrongGuan
  github_username:  DengrongGuan12
  linkedin_username:  DengrongGuan
  facebook_username: 管登荣

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
